// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: myproto.proto

//指定包名

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义枚举
type Week int32

const (
	Week_Monday   Week = 0 //枚举值必须从0开始
	Week_Turesday Week = 1
)

// Enum value maps for Week.
var (
	Week_name = map[int32]string{
		0: "Monday",
		1: "Turesday",
	}
	Week_value = map[string]int32{
		"Monday":   0,
		"Turesday": 1,
	}
)

func (x Week) Enum() *Week {
	p := new(Week)
	*p = x
	return p
}

func (x Week) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Week) Descriptor() protoreflect.EnumDescriptor {
	return file_myproto_proto_enumTypes[0].Descriptor()
}

func (Week) Type() protoreflect.EnumType {
	return &file_myproto_proto_enumTypes[0]
}

func (x Week) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Week.Descriptor instead.
func (Week) EnumDescriptor() ([]byte, []int) {
	return file_myproto_proto_rawDescGZIP(), []int{0}
}

// 消息体可以嵌套
type People struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        int32                  `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *People) Reset() {
	*x = People{}
	mi := &file_myproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *People) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*People) ProtoMessage() {}

func (x *People) ProtoReflect() protoreflect.Message {
	mi := &file_myproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use People.ProtoReflect.Descriptor instead.
func (*People) Descriptor() ([]byte, []int) {
	return file_myproto_proto_rawDescGZIP(), []int{0}
}

func (x *People) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// 定义消息体
type Student struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Age   int32                  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"` //可以不从1开始，但是不能重复
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	P     *People                `protobuf:"bytes,3,opt,name=p,proto3" json:"p,omitempty"`
	Score []int32                `protobuf:"varint,4,rep,packed,name=score,proto3" json:"score,omitempty"` //数组
	// 枚举
	W Week `protobuf:"varint,5,opt,name=w,proto3,enum=pb.Week" json:"w,omitempty"`
	// 联合体
	//
	// Types that are valid to be assigned to Data:
	//
	//	*Student_Teacher
	//	*Student_Class
	Data          isStudent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_myproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_myproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_myproto_proto_rawDescGZIP(), []int{1}
}

func (x *Student) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetP() *People {
	if x != nil {
		return x.P
	}
	return nil
}

func (x *Student) GetScore() []int32 {
	if x != nil {
		return x.Score
	}
	return nil
}

func (x *Student) GetW() Week {
	if x != nil {
		return x.W
	}
	return Week_Monday
}

func (x *Student) GetData() isStudent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Student) GetTeacher() string {
	if x != nil {
		if x, ok := x.Data.(*Student_Teacher); ok {
			return x.Teacher
		}
	}
	return ""
}

func (x *Student) GetClass() string {
	if x != nil {
		if x, ok := x.Data.(*Student_Class); ok {
			return x.Class
		}
	}
	return ""
}

type isStudent_Data interface {
	isStudent_Data()
}

type Student_Teacher struct {
	Teacher string `protobuf:"bytes,6,opt,name=teacher,proto3,oneof"`
}

type Student_Class struct {
	Class string `protobuf:"bytes,7,opt,name=class,proto3,oneof"`
}

func (*Student_Teacher) isStudent_Data() {}

func (*Student_Class) isStudent_Data() {}

var File_myproto_proto protoreflect.FileDescriptor

const file_myproto_proto_rawDesc = "" +
	"\n" +
	"\rmyproto.proto\x12\x02pb\" \n" +
	"\x06People\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x05R\x06weight\"\xb3\x01\n" +
	"\aStudent\x12\x10\n" +
	"\x03age\x18\x01 \x01(\x05R\x03age\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\x01p\x18\x03 \x01(\v2\n" +
	".pb.PeopleR\x01p\x12\x14\n" +
	"\x05score\x18\x04 \x03(\x05R\x05score\x12\x16\n" +
	"\x01w\x18\x05 \x01(\x0e2\b.pb.WeekR\x01w\x12\x1a\n" +
	"\ateacher\x18\x06 \x01(\tH\x00R\ateacher\x12\x16\n" +
	"\x05class\x18\a \x01(\tH\x00R\x05classB\x06\n" +
	"\x04data* \n" +
	"\x04Week\x12\n" +
	"\n" +
	"\x06Monday\x10\x00\x12\f\n" +
	"\bTuresday\x10\x012&\n" +
	"\x04bj38\x12\x1e\n" +
	"\x03Say\x12\n" +
	".pb.People\x1a\v.pb.StudentB\aZ\x05../pbb\x06proto3"

var (
	file_myproto_proto_rawDescOnce sync.Once
	file_myproto_proto_rawDescData []byte
)

func file_myproto_proto_rawDescGZIP() []byte {
	file_myproto_proto_rawDescOnce.Do(func() {
		file_myproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myproto_proto_rawDesc), len(file_myproto_proto_rawDesc)))
	})
	return file_myproto_proto_rawDescData
}

var file_myproto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_myproto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_myproto_proto_goTypes = []any{
	(Week)(0),       // 0: pb.Week
	(*People)(nil),  // 1: pb.People
	(*Student)(nil), // 2: pb.Student
}
var file_myproto_proto_depIdxs = []int32{
	1, // 0: pb.Student.p:type_name -> pb.People
	0, // 1: pb.Student.w:type_name -> pb.Week
	1, // 2: pb.bj38.Say:input_type -> pb.People
	2, // 3: pb.bj38.Say:output_type -> pb.Student
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_myproto_proto_init() }
func file_myproto_proto_init() {
	if File_myproto_proto != nil {
		return
	}
	file_myproto_proto_msgTypes[1].OneofWrappers = []any{
		(*Student_Teacher)(nil),
		(*Student_Class)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myproto_proto_rawDesc), len(file_myproto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myproto_proto_goTypes,
		DependencyIndexes: file_myproto_proto_depIdxs,
		EnumInfos:         file_myproto_proto_enumTypes,
		MessageInfos:      file_myproto_proto_msgTypes,
	}.Build()
	File_myproto_proto = out.File
	file_myproto_proto_goTypes = nil
	file_myproto_proto_depIdxs = nil
}
